import type { Metadata } from "next";
import "../styles/tailwind/main.css";


export const metadata: Metadata = {
  title: "Mikro LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased mx-16`}>      
        {children}
      </body>
    </html>
  );
}
import React, { Suspense } from "react";


